/*
 * Users
 * API to register user device
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@marax.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2002Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-20T11:49:25.649Z[GMT]")
public class InlineResponse2002Data {
  @SerializedName("maraxId")
  private String maraxId = null;

  public InlineResponse2002Data maraxId(String maraxId) {
    this.maraxId = maraxId;
    return this;
  }

   /**
   * Get maraxId
   * @return maraxId
  **/
  @Schema(example = "5dea270154d7e928727c1cd9", description = "")
  public String getMaraxId() {
    return maraxId;
  }

  public void setMaraxId(String maraxId) {
    this.maraxId = maraxId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002Data inlineResponse2002Data = (InlineResponse2002Data) o;
    return Objects.equals(this.maraxId, inlineResponse2002Data.maraxId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maraxId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002Data {\n");
    
    sb.append("    maraxId: ").append(toIndentedString(maraxId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
