/*
 * Users
 * API to register user device
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@marax.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.UserSdkAndroid;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * UserSdk
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-20T11:49:25.649Z[GMT]")
public class UserSdk {
  @SerializedName("android")
  private List<UserSdkAndroid> android = null;

  public UserSdk android(List<UserSdkAndroid> android) {
    this.android = android;
    return this;
  }

  public UserSdk addAndroidItem(UserSdkAndroid androidItem) {
    if (this.android == null) {
      this.android = new ArrayList<UserSdkAndroid>();
    }
    this.android.add(androidItem);
    return this;
  }

   /**
   * Get android
   * @return android
  **/
  @Schema(description = "")
  public List<UserSdkAndroid> getAndroid() {
    return android;
  }

  public void setAndroid(List<UserSdkAndroid> android) {
    this.android = android;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSdk userSdk = (UserSdk) o;
    return Objects.equals(this.android, userSdk.android);
  }

  @Override
  public int hashCode() {
    return Objects.hash(android);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSdk {\n");
    
    sb.append("    android: ").append(toIndentedString(android)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
