/*
 * Users
 * API to register user device
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@marax.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.UserAttributes;
import io.swagger.client.model.UserCompliances;
import io.swagger.client.model.UserSdk;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * User
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-12-20T11:49:25.649Z[GMT]")
public class User {
  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("identities")
  private Object identities = null;

  @SerializedName("sdk")
  private UserSdk sdk = null;

  @SerializedName("compliances")
  private UserCompliances compliances = null;

  @SerializedName("attributes")
  private UserAttributes attributes = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public User deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @Schema(example = "9125a8dc-52ee-365b-a5aa-81b0b3681cf6", description = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public User identities(Object identities) {
    this.identities = identities;
    return this;
  }

   /**
   * Get identities
   * @return identities
  **/
  @Schema(description = "")
  public Object getIdentities() {
    return identities;
  }

  public void setIdentities(Object identities) {
    this.identities = identities;
  }

  public User sdk(UserSdk sdk) {
    this.sdk = sdk;
    return this;
  }

   /**
   * Get sdk
   * @return sdk
  **/
  @Schema(description = "")
  public UserSdk getSdk() {
    return sdk;
  }

  public void setSdk(UserSdk sdk) {
    this.sdk = sdk;
  }

  public User compliances(UserCompliances compliances) {
    this.compliances = compliances;
    return this;
  }

   /**
   * Get compliances
   * @return compliances
  **/
  @Schema(description = "")
  public UserCompliances getCompliances() {
    return compliances;
  }

  public void setCompliances(UserCompliances compliances) {
    this.compliances = compliances;
  }

  public User attributes(UserAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(description = "")
  public UserAttributes getAttributes() {
    return attributes;
  }

  public void setAttributes(UserAttributes attributes) {
    this.attributes = attributes;
  }

  public User createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(example = "2019-12-10T09:15:03.534+00:00", description = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public User updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(example = "2019-12-10T09:15:03.534+00:00", description = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.deviceId, user.deviceId) &&
        Objects.equals(this.identities, user.identities) &&
        Objects.equals(this.sdk, user.sdk) &&
        Objects.equals(this.compliances, user.compliances) &&
        Objects.equals(this.attributes, user.attributes) &&
        Objects.equals(this.createdAt, user.createdAt) &&
        Objects.equals(this.updatedAt, user.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, identities, sdk, compliances, attributes, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    identities: ").append(toIndentedString(identities)).append("\n");
    sb.append("    sdk: ").append(toIndentedString(sdk)).append("\n");
    sb.append("    compliances: ").append(toIndentedString(compliances)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
