/*
 * Users
 * API to register user device
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@marax.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body1;
import io.swagger.client.model.Body2;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse2002;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Register a new device
     *
     * New devices are registered 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerDeviceTokenTest() throws ApiException {
        Body2 body = null;
        InlineResponse2002 response = api.registerDeviceToken(body);

        // TODO: test validations
    }
    /**
     * Update the firebase token for a device
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDeviceTokenTest() throws ApiException {
        Body1 body = null;
        InlineResponse2001 response = api.updateDeviceToken(body);

        // TODO: test validations
    }
}
