/*
 * Users
 * API to register user device
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@marax.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserOffersApi
 */
@Ignore
public class UserOffersApiTest {

    private final UserOffersApi api = new UserOffersApi();

    /**
     * Fetch a single offer for user by offer id
     *
     * Returns a single offer for the user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchOfferTest() throws ApiException {
        String userId = null;
        String offerId = null;
        InlineResponse200 response = api.fetchOffer(userId, offerId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paintOfferTest() throws ApiException {
        String userId = null;
        String templateId = null;
        String response = api.paintOffer(userId, templateId);

        // TODO: test validations
    }
    /**
     * Update the offer details for the user
     *
     * Updates the &#x27;status&#x27; of the offer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateOfferTest() throws ApiException {
        Body body = null;
        String userId = null;
        String offerId = null;
        InlineResponse2001 response = api.updateOffer(body, userId, offerId);

        // TODO: test validations
    }
}
